# Generated by Django 4.0.3 on 2022-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_fips_statepop_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='fipsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('countyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='fips',
        ),
        migrations.DeleteModel(
            name='statePop',
        ),
    ]
