# Generated by Django 4.0.3 on 2022-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_fipscode_delete_fips_delete_statepop'),
    ]

    operations = [
        migrations.CreateModel(
            name='statePop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=255)),
                ('popest2021', models.IntegerField()),
            ],
        ),
    ]
